# Generated by Django 4.2.2 on 2023-07-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_category_alter_bid_sum_alter_listing_current_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
